insert into Users (id, first_name, last_name, email, address, username, password) values (1, 'Brice', 'Franklin', 'bfranklin0@tumblr.com', '78465 Express Court', 'bfranklin0', 'fC7IkfT0ZZs');
insert into Users (id, first_name, last_name, email, address, username, password) values (2, 'Brena', 'Astupenas', 'bastupenas1@symantec.com', '95020 Raven Circle', 'bastupenas1', 'hus7HVKQR');
insert into Users (id, first_name, last_name, email, address, username, password) values (3, 'Bonnee', 'Boultwood', 'bboultwood2@google.de', '83 Holy Cross Court', 'bboultwood2', 'Yqm2Hcuxgve');
insert into Users (id, first_name, last_name, email, address, username, password) values (4, 'Joyce', 'Hercock', 'jhercock3@whitehouse.gov', '0 Melrose Hill', 'jhercock3', 'M6BqJlKs');
insert into Users (id, first_name, last_name, email, address, username, password) values (5, 'Stefa', 'Monnery', 'smonnery4@shinystat.com', '103 Troy Crossing', 'smonnery4', 'p5DQdVXJ');
insert into Users (id, first_name, last_name, email, address, username, password) values (6, 'Merilee', 'Stickney', 'mstickney5@acquirethisname.com', '9532 Eastlawn Way', 'mstickney5', 'tRheaSXsmbI');
insert into Users (id, first_name, last_name, email, address, username, password) values (7, 'Buffy', 'Obell', 'bobell6@adobe.com', '460 Vahlen Drive', 'bobell6', 'UEB45byKT');
insert into Users (id, first_name, last_name, email, address, username, password) values (8, 'Xaviera', 'Redmayne', 'xredmayne7@cnn.com', '625 Debs Trail', 'xredmayne7', 'oJmdpmsk');
insert into Users (id, first_name, last_name, email, address, username, password) values (9, 'Amaleta', 'Oleksiak', 'aoleksiak8@storify.com', '62238 Glendale Plaza', 'aoleksiak8', 'QH6PP5rEHVPJ');
insert into Users (id, first_name, last_name, email, address, username, password) values (10, 'Cozmo', 'Lejeune', 'clejeune9@bbb.org', '65715 Darwin Drive', 'clejeune9', 'fBwPkNzsj5b2');
insert into Users (id, first_name, last_name, email, address, username, password) values (11, 'Sky', 'Jerdein', 'sjerdeina@example.com', '695 Anniversary Place', 'sjerdeina', 'ajemvVDtcV');
insert into Users (id, first_name, last_name, email, address, username, password) values (12, 'Jere', 'Guilford', 'jguilfordb@vimeo.com', '14 Brickson Park Way', 'jguilfordb', 'CPqTqi0Ll');
insert into Users (id, first_name, last_name, email, address, username, password) values (13, 'Sauveur', 'Chipp', 'schippc@slideshare.net', '35032 Washington Street', 'schippc', 'Ejom28zTcbhg');
insert into Users (id, first_name, last_name, email, address, username, password) values (14, 'Zeb', 'Rambaut', 'zrambautd@slate.com', '13 Florence Trail', 'zrambautd', 'SklWSN0zf');
insert into Users (id, first_name, last_name, email, address, username, password) values (15, 'Irwin', 'Critoph', 'icritophe@rediff.com', '0633 Northport Hill', 'icritophe', '2JpJjmc');
insert into Users (id, first_name, last_name, email, address, username, password) values (16, 'Donnell', 'Carnilian', 'dcarnilianf@csmonitor.com', '4 Bonner Pass', 'dcarnilianf', 'GxFqksX');
insert into Users (id, first_name, last_name, email, address, username, password) values (17, 'Isabel', 'Mangenot', 'imangenotg@rediff.com', '7 Mifflin Place', 'imangenotg', 'TWHHZsDsF');
insert into Users (id, first_name, last_name, email, address, username, password) values (18, 'De witt', 'Bailey', 'dbaileyh@networksolutions.com', '1928 Harbort Lane', 'dbaileyh', 'BL2Y0IYYJ');
insert into Users (id, first_name, last_name, email, address, username, password) values (19, 'Jesse', 'Caldaro', 'jcaldaroi@youtu.be', '00746 Gulseth Junction', 'jcaldaroi', 'AjjEv0a1wZ');
insert into Users (id, first_name, last_name, email, address, username, password) values (20, 'Romain', 'Clyburn', 'rclyburnj@businesswire.com', '9190 Trailsway Terrace', 'rclyburnj', 'Tx2Cs1pr2oB');
